spring:
  freemarker:
    template-loader-path: "classpath:/templates"
    suffix: ".ftl"
  security.user:
    name: ${ADMIN_USERNAME:admin}
    password: ${ADMIN_PASSWORD:admin}
app:
  baseUrl: ${APP_BASE_URL:http://localhost:8080}
  adminPanelUrl: ${ADMIN_PANEL_URL:admin}

# ===============================
# DATABASE
# ===============================
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto: update
spring.jpa.show-sql: true
spring.jpa.generate-ddl: true
spring.datasource.url: ${DB_URL:jdbc:postgresql://localhost:5432/trading_db}
spring.datasource.username: ${DB_USERNAME:postgres}
spring.datasource.password: ${DB_PASSWORD:postgres}